/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.PenambahanControl;
import control.ObatControl;
import exception.InputanKosongException;
import java.net.URI;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.Obat;
import model.User;
import model.Penambahan;
import table.TableObat;
/**
 *
 * 
 */
public class PenambahanView extends javax.swing.JFrame {

    /**
     * Creates new form PenambahanView
     */
    private PenambahanControl penambahanControl;
    private ObatControl obatControl;
    Obat o;
    Penambahan n;
    User u;
    List<Obat> listObat;
    String action = "";
    String selectedValue = "";
    
    public PenambahanView() {
        initComponents();
        penambahanControl = new PenambahanControl();
        obatControl = new ObatControl();
        idInput.setEnabled(false);
        stokInput.setEnabled(false);
        setEditDeleteBtn(false);
        clearText();
        showDataObat();
    }
    
    public void setUser(String userName, String password, String jenisAkses, String nama){
        userNameLabel.setText(userName);
        passwordLabel.setText(password);
        jenisAksesLabel.setText(jenisAkses);
        namaUserLabel.setText(nama);
        namaUserLabel.setVisible(false);
        passwordLabel.setVisible(false);
        jenisAksesLabel.setVisible(false);
        u = new User(userNameLabel.getText(), passwordLabel.getText(), jenisAksesLabel.getText(), namaUserLabel.getText());
    }
    
    public void setEditDeleteBtn(boolean value){
       editBtn.setEnabled(value);
       deleteBtn.setEnabled(value);
    }
    
    public void setComponent(boolean value){
        namaInput.setEnabled(value);
        jenisDropdown.setEnabled(value);
        hargaInput.setEnabled(value);
        jumlahTambahInput.setEnabled(value);
    }
    
    public void clearText(){
        idInput.setText("AUTO GENERATE");
        namaInput.setText("");
        jenisDropdown.setSelectedItem(ABORT);
        hargaInput.setText("");
        stokInput.setText("");
        jumlahTambahInput.setText("");
        
        searchInput.setText("");
    }
    
    public void showDataObat(){
        obatTable.setModel(obatControl.showDataObat(""));
    }
    
    public void inputanKosongException() throws InputanKosongException {
        if(jenisDropdown.getSelectedIndex() == -1 || idInput.getText().isEmpty() || namaInput.getText().isEmpty() ||
                hargaInput.getText().isEmpty() || jumlahTambahInput.getText().isEmpty()){
            throw new InputanKosongException();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPenambahanPanel = new javax.swing.JPanel();
        topPenambahanPanel = new javax.swing.JPanel();
        penambahanLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        inputPanel = new javax.swing.JPanel();
        deleteBtn = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        namaLabel = new javax.swing.JLabel();
        namaInput = new javax.swing.JTextField();
        jenisLabel = new javax.swing.JLabel();
        jenisDropdown = new javax.swing.JComboBox<>();
        hargaLabel = new javax.swing.JLabel();
        hargaInput = new javax.swing.JTextField();
        jumlahTambahLabel = new javax.swing.JLabel();
        jumlahTambahInput = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        historyBtn = new javax.swing.JButton();
        userNameLabel = new javax.swing.JLabel();
        namaUserLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        jenisAksesLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        stokObatLabel = new javax.swing.JLabel();
        stokInput = new javax.swing.JTextField();
        tablePanel = new javax.swing.JPanel();
        searchInput = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        obatTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPenambahanPanel.setBackground(new java.awt.Color(255, 255, 102));

        topPenambahanPanel.setBackground(new java.awt.Color(204, 204, 0));

        penambahanLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        penambahanLabel.setForeground(new java.awt.Color(0, 0, 0));
        penambahanLabel.setText("Penambahan");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pharmacyLogo.png"))); // NOI18N

        logoutBtn.setBackground(new java.awt.Color(255, 255, 255));
        logoutBtn.setForeground(new java.awt.Color(0, 0, 0));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logoutLogo.png"))); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPenambahanPanelLayout = new javax.swing.GroupLayout(topPenambahanPanel);
        topPenambahanPanel.setLayout(topPenambahanPanelLayout);
        topPenambahanPanelLayout.setHorizontalGroup(
            topPenambahanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPenambahanPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(penambahanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addGap(35, 35, 35))
        );
        topPenambahanPanelLayout.setVerticalGroup(
            topPenambahanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPenambahanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPenambahanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(penambahanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        inputPanel.setBackground(new java.awt.Color(255, 255, 102));

        deleteBtn.setBackground(new java.awt.Color(255, 51, 51));
        deleteBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        idLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(0, 0, 0));
        idLabel.setText("Id Obat");

        idInput.setBackground(new java.awt.Color(255, 255, 255));
        idInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        idInput.setForeground(new java.awt.Color(0, 0, 0));

        namaLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        namaLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaLabel.setText("Nama Obat");

        namaInput.setBackground(new java.awt.Color(255, 255, 255));
        namaInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namaInput.setForeground(new java.awt.Color(0, 0, 0));

        jenisLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jenisLabel.setForeground(new java.awt.Color(0, 0, 0));
        jenisLabel.setText("Jenis Obat");

        jenisDropdown.setBackground(new java.awt.Color(255, 255, 255));
        jenisDropdown.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jenisDropdown.setForeground(new java.awt.Color(0, 0, 0));
        jenisDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tablet", "Sirup", "Bubuk" }));

        hargaLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        hargaLabel.setForeground(new java.awt.Color(0, 0, 0));
        hargaLabel.setText("Harga Obat");

        hargaInput.setBackground(new java.awt.Color(255, 255, 255));
        hargaInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hargaInput.setForeground(new java.awt.Color(0, 0, 0));

        jumlahTambahLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jumlahTambahLabel.setForeground(new java.awt.Color(0, 0, 0));
        jumlahTambahLabel.setText("Stok Obat Baru");

        jumlahTambahInput.setBackground(new java.awt.Color(255, 255, 255));
        jumlahTambahInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jumlahTambahInput.setForeground(new java.awt.Color(0, 0, 0));

        saveBtn.setBackground(new java.awt.Color(102, 153, 0));
        saveBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(204, 51, 0));
        cancelBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(255, 204, 51));
        editBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        historyBtn.setBackground(new java.awt.Color(0, 153, 102));
        historyBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        historyBtn.setForeground(new java.awt.Color(255, 255, 255));
        historyBtn.setText("History");
        historyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyBtnActionPerformed(evt);
            }
        });

        userNameLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        userNameLabel.setText("userName");

        namaUserLabel.setText("namaUser");

        passwordLabel.setText("passwordUser");

        jenisAksesLabel.setText("jenisUser");

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Welcome Back, ");

        stokObatLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        stokObatLabel.setForeground(new java.awt.Color(0, 0, 0));
        stokObatLabel.setText("Stok Obat");

        stokInput.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idLabel)
                    .addComponent(jumlahTambahLabel)
                    .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jumlahTambahInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(hargaInput, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(inputPanelLayout.createSequentialGroup()
                                        .addComponent(namaLabel)
                                        .addGap(230, 230, 230))
                                    .addGroup(inputPanelLayout.createSequentialGroup()
                                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(184, 184, 184)))
                                .addComponent(historyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(inputPanelLayout.createSequentialGroup()
                                    .addComponent(jenisLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stokObatLabel))
                                .addComponent(namaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(inputPanelLayout.createSequentialGroup()
                            .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(stokInput, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, inputPanelLayout.createSequentialGroup()
                                        .addComponent(hargaLabel)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(37, 37, 37)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameLabel)))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jenisDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addComponent(jenisAksesLabel)
                                .addGap(18, 18, 18)
                                .addComponent(namaUserLabel))
                            .addComponent(passwordLabel))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(historyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(userNameLabel))))
                .addGap(18, 18, 18)
                .addComponent(idLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addGap(11, 11, 11)
                .addComponent(namaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jenisAksesLabel)
                    .addComponent(namaUserLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisLabel)
                    .addComponent(stokObatLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stokInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(hargaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jumlahTambahLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jumlahTambahInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablePanel.setBackground(new java.awt.Color(255, 204, 102));

        searchInput.setBackground(new java.awt.Color(255, 255, 255));
        searchInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchInput.setForeground(new java.awt.Color(0, 0, 0));

        searchBtn.setBackground(new java.awt.Color(153, 255, 102));
        searchBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        obatTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        obatTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                obatTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(obatTable);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPenambahanPanelLayout = new javax.swing.GroupLayout(mainPenambahanPanel);
        mainPenambahanPanel.setLayout(mainPenambahanPanelLayout);
        mainPenambahanPanelLayout.setHorizontalGroup(
            mainPenambahanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPenambahanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPenambahanPanelLayout.createSequentialGroup()
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPenambahanPanelLayout.setVerticalGroup(
            mainPenambahanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPenambahanPanelLayout.createSequentialGroup()
                .addComponent(topPenambahanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPenambahanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPenambahanPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPenambahanPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        setEditDeleteBtn(false);
        setComponent(true);
        clearText();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try{
            inputanKosongException();
            selectedValue = jenisDropdown.getSelectedItem().toString();
            
            if(action.equalsIgnoreCase("Update")){
                int jumlahSelisih = (Integer.parseInt(jumlahTambahInput.getText()) - Integer.parseInt(stokInput.getText()));
                o = new Obat(Integer.parseInt(idInput.getText()), namaInput.getText(), selectedValue, Integer.parseInt(jumlahTambahInput.getText()), Double.parseDouble(hargaInput.getText()));
                obatControl.updateDataObat(o);
                
                n = new Penambahan(jumlahSelisih, u, o);
                penambahanControl.insertDataPenambahan(n);
                JOptionPane.showMessageDialog(this, "Data Obat berhasil di Update");
                
            } else{
                o = new Obat(namaInput.getText(), selectedValue, Integer.parseInt(jumlahTambahInput.getText()), Double.parseDouble(hargaInput.getText()));
                obatControl.insertDataObat(o);
                
                n = new Penambahan(Integer.parseInt(jumlahTambahInput.getText()), u, o);
                penambahanControl.insertDataPenambahan(n);
                JOptionPane.showMessageDialog(this, "Data Obat baru berhasil ditambahkan");
            }
            setEditDeleteBtn(false);
            setComponent(true);
            action = "";
            clearText();
            showDataObat();
            
        } catch(InputanKosongException e){
            JOptionPane.showMessageDialog(this, e.message());
        } catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Inputan harus angka");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        jenisDropdown.setEnabled(true);
        hargaInput.setEnabled(true);
        jumlahTambahInput.setEnabled(true);
        action = "Update";
    }//GEN-LAST:event_editBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        try{
            TableObat tObat = obatControl.showDataObat(searchInput.getText());
            if(tObat.getRowCount() == 0){
                clearText();
                JOptionPane.showMessageDialog(this, "Data Obat tidak ditemukan");
            } else{
                obatTable.setModel(tObat);
            }
            clearText();
            
        } catch(Exception e){
            System.out.println("Error : " + e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void obatTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_obatTableMouseClicked
        setEditDeleteBtn(true);
        setComponent(false);
        
        int clickedRow = obatTable.getSelectedRow();
        TableModel tableModel = obatTable.getModel();
        
        idInput.setText(tableModel.getValueAt(clickedRow, 0).toString());
        namaInput.setText(tableModel.getValueAt(clickedRow, 1).toString());
        jenisDropdown.setSelectedItem(tableModel.getValueAt(clickedRow, 2).toString());
        hargaInput.setText(tableModel.getValueAt(clickedRow, 3).toString());
        stokInput.setText(tableModel.getValueAt(clickedRow, 4).toString());
    }//GEN-LAST:event_obatTableMouseClicked

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin menghapus data obat ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        switch(getAnswer){
            case 0 : 
                // Jika Jawaban User : Yes
                try{
                    o = new Obat(Integer.parseInt(idInput.getText()), namaInput.getText(), selectedValue, Integer.parseInt(stokInput.getText()), Double.parseDouble(hargaInput.getText()));
                    obatControl.deleteDataObat(Integer.parseInt(idInput.getText()));
                    
                    int jumlahDelete = (0 - Integer.parseInt(stokInput.getText()));
                    n = new Penambahan(jumlahDelete, u, o);
                    penambahanControl.insertDataPenambahan(n);
                    
                    clearText();
                    showDataObat();
                    setEditDeleteBtn(false);
                
                } catch(Exception e){
                    System.out.println("Error : " + e.getMessage());
                }
                break;
            
            case 1 :
                // Jika Jawaban User : No
                break;
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void historyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyBtnActionPerformed
       HistoryView hv = new HistoryView();
       hv.setUser(userNameLabel.getText(), passwordLabel.getText(), jenisAksesLabel.getText(), namaUserLabel.getText());
       this.dispose();
       hv.setVisible(true);
    }//GEN-LAST:event_historyBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        UserLoginView uv = new UserLoginView();
        JOptionPane.showMessageDialog(this, "Logout success");
        this.dispose();
        uv.setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenambahanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenambahanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenambahanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenambahanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenambahanView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField hargaInput;
    private javax.swing.JLabel hargaLabel;
    private javax.swing.JButton historyBtn;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel idLabel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jenisAksesLabel;
    private javax.swing.JComboBox<String> jenisDropdown;
    private javax.swing.JLabel jenisLabel;
    private javax.swing.JTextField jumlahTambahInput;
    private javax.swing.JLabel jumlahTambahLabel;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mainPenambahanPanel;
    private javax.swing.JTextField namaInput;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel namaUserLabel;
    private javax.swing.JTable obatTable;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel penambahanLabel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchInput;
    private javax.swing.JTextField stokInput;
    private javax.swing.JLabel stokObatLabel;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JPanel topPenambahanPanel;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
